# -*- coding: utf-8 -*-
"""Fetal_Health.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BN8VELguDxGAFWTffwI0BogSh2IqSz_l
"""

!pip install catboost scikit-learn pandas matplotlib seaborn

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif, mutual_info_classif

from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

from xgboost import XGBClassifier
from catboost import CatBoostClassifier

import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("fetal_health.csv")
df.head()

X = df.drop("fetal_health", axis=1)
y = df["fetal_health"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = {
    "RF": RandomForestClassifier(),
    "KNN": KNeighborsClassifier(),
    "DT": DecisionTreeClassifier(),
    "SVM": SVC(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss'),
    "CatBoost": CatBoostClassifier(verbose=0)
}

def evaluate_models(X_tr, X_te, y_tr, y_te):
    results = {}

    for name, model in models.items():
        model.fit(X_tr, y_tr)
        y_pred = model.predict(X_te)

        results[name] = [
            accuracy_score(y_te, y_pred),
            precision_score(y_te, y_pred, average='weighted'),
            recall_score(y_te, y_pred, average='weighted'),
            f1_score(y_te, y_pred, average='weighted')
        ]

    return pd.DataFrame(results, index=["Accuracy", "Precision", "Recall", "F1"]).T

print("\n📊 TABLE 1: WITHOUT FEATURE SELECTION")

df_no_fs = evaluate_models(X_train, X_test, y_train - 1, y_test - 1)
print(df_no_fs)

from sklearn.feature_selection import SelectKBest, f_classif, mutual_info_classif
from sklearn.metrics import accuracy_score
from catboost import CatBoostClassifier

feature_sizes = list(range(2, 22))

mi_acc = []
anova_acc = []
cc_acc = []

# Correlation computed once
corr = df.corr()["fetal_health"].abs().sort_values(ascending=False)[1:]

for k in feature_sizes:

    model = CatBoostClassifier(verbose=0, random_state=42)

    # 🔹 MUTUAL INFORMATION
    selector_mi = SelectKBest(mutual_info_classif, k=k)
    X_train_mi = selector_mi.fit_transform(X_train, y_train - 1)
    X_test_mi = selector_mi.transform(X_test)

    model.fit(X_train_mi, y_train - 1)
    y_pred_mi = model.predict(X_test_mi)
    mi_acc.append(accuracy_score(y_test - 1, y_pred_mi))


    # 🔹 ANOVA
    selector_anova = SelectKBest(f_classif, k=k)
    X_train_anova = selector_anova.fit_transform(X_train, y_train - 1)
    X_test_anova = selector_anova.transform(X_test)

    model.fit(X_train_anova, y_train - 1)
    y_pred_anova = model.predict(X_test_anova)
    anova_acc.append(accuracy_score(y_test - 1, y_pred_anova))


    # 🔹 CORRELATION (FIXED PART ✅)
    top_features = corr.index[:k]

    X_train_cc = pd.DataFrame(X_train, columns=df.columns[:-1])[top_features]
    X_test_cc = pd.DataFrame(X_test, columns=df.columns[:-1])[top_features]

    model.fit(X_train_cc, y_train - 1)
    y_pred_cc = model.predict(X_test_cc)
    cc_acc.append(accuracy_score(y_test - 1, y_pred_cc))


print("mi_acc:", mi_acc)
print("anova_acc:", anova_acc)
print("cc_acc:", cc_acc)
print("feature_sizes:", feature_sizes)

table2 = pd.DataFrame({
    "MI": mi_acc,
    "ANOVA": anova_acc,
    "CC": cc_acc
}, index=feature_sizes)

table2.index.name = "Feature set size"

table2 = table2.round(2)

print("\n📊 TABLE 2 (FINAL - PAPER STYLE)")
print(table2.to_string())

from sklearn.feature_selection import mutual_info_classif

# Compute MI scores
mi_scores = mutual_info_classif(X, y)

# Create DataFrame
mi_df = pd.DataFrame({
    "Feature": df.columns[:-1],
    "Score": mi_scores
})

# Sort features
mi_df = mi_df.sort_values(by="Score", ascending=False)

# 🔥 BIGGER + CLEANER PLOT (PAPER STYLE)
plt.figure(figsize=(16,6))  # wider like paper

bars = plt.bar(mi_df["Feature"], mi_df["Score"])

plt.title("Fig. 2: Ranking of Features (Mutual Information)", fontsize=14)
plt.xlabel("Features", fontsize=12)
plt.ylabel("MI Score", fontsize=12)

plt.xticks(rotation=60, ha='right', fontsize=10)
plt.yticks(fontsize=10)

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

plt.figure(figsize=(18,6))

plt.bar(mi_df["Feature"], mi_df["Score"], edgecolor='black')

plt.title("Ranking of Features using Mutual Information", fontsize=14)
plt.xlabel("Features")
plt.ylabel("Score")

plt.xticks(rotation=65, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

from sklearn.feature_selection import f_classif

# Compute ANOVA scores
anova_scores, _ = f_classif(X, y)

# Create DataFrame
anova_df = pd.DataFrame({
    "Feature": df.columns[:-1],
    "Score": anova_scores
})

# Sort features (descending)
anova_df = anova_df.sort_values(by="Score", ascending=False)

# 🔥 PLOT (MATCH FIG 2 STYLE)
plt.figure(figsize=(18,6))

plt.bar(anova_df["Feature"], anova_df["Score"], edgecolor='black')

plt.title("Fig. 3: Ranking of Features (ANOVA)", fontsize=14)
plt.xlabel("Features", fontsize=12)
plt.ylabel("F-Score", fontsize=12)

plt.xticks(rotation=65, ha='right', fontsize=10)
plt.yticks(fontsize=10)

plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

# Compute correlation with target
corr_values = df.corr()["fetal_health"].drop("fetal_health")

# Take absolute values (important!)
corr_values = corr_values.abs()

# Convert to DataFrame
corr_df = corr_values.sort_values(ascending=False).reset_index()
corr_df.columns = ["Feature", "Score"]

# 🔥 PLOT (MATCH FIG 2 & 3 STYLE)
plt.figure(figsize=(18,6))

plt.bar(corr_df["Feature"], corr_df["Score"], edgecolor='black')

plt.title("Fig. 4: Ranking of Features (Correlation Coefficient)", fontsize=14)
plt.xlabel("Features", fontsize=12)
plt.ylabel("Correlation Score", fontsize=12)

plt.xticks(rotation=65, ha='right', fontsize=10)
plt.yticks(fontsize=10)

plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

# Compute correlation with target
corr_values = df.corr()["fetal_health"].drop("fetal_health")

# Take absolute values (important!)
corr_values = corr_values.abs()

# Convert to DataFrame
corr_df = corr_values.sort_values(ascending=False).reset_index()
corr_df.columns = ["Feature", "Score"]

# 🔥 PLOT (MATCH FIG 2 & 3 STYLE)
plt.figure(figsize=(18,6))

plt.bar(corr_df["Feature"], corr_df["Score"], edgecolor='black')

plt.title("Fig. 4: Ranking of Features (Correlation Coefficient)", fontsize=14)
plt.xlabel("Features", fontsize=12)
plt.ylabel("Correlation Score", fontsize=12)

plt.xticks(rotation=65, ha='right', fontsize=10)
plt.yticks(fontsize=10)

plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

from sklearn.feature_selection import SelectKBest, f_classif

anova = SelectKBest(f_classif, k=14)
X_best = anova.fit_transform(X, y)

X_train, X_test, y_train, y_test = train_test_split(
    X_best, y, test_size=0.2, random_state=42
)

model = CatBoostClassifier(verbose=0, random_state=42)
model.fit(X_train, y_train - 1)

y_pred = model.predict(X_test)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test - 1, y_pred)

labels = ["Normal", "Suspicious", "Pathologic"]

plt.figure(figsize=(6,5))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels,
            yticklabels=labels)

plt.title("Fig. 5: Confusion Matrix (CatBoost with ANOVA)", fontsize=13)
plt.xlabel("Predicted Label", fontsize=11)
plt.ylabel("True Label", fontsize=11)

plt.xticks(fontsize=10)
plt.yticks(fontsize=10)

plt.tight_layout()
plt.show()

model_all = CatBoostClassifier(verbose=0, random_state=42)

# Using the full training and testing datasets (X_train, X_test) that were previously defined
model_all.fit(X_train, y_train - 1)
y_pred_all = model_all.predict(X_test)

# Already done earlier, just reuse if available

model_14 = CatBoostClassifier(verbose=0, random_state=42)
model_14.fit(X_train, y_train - 1)
y_pred_14 = model_14.predict(X_test)

from sklearn.metrics import precision_recall_fscore_support

# All features
prec_all, rec_all, f1_all, _ = precision_recall_fscore_support(
    y_test - 1, y_pred_all
)

# 14 features
prec_14, rec_14, f1_14, _ = precision_recall_fscore_support(
    y_test - 1, y_pred_14
)

classes = ["Normal (1)", "Suspicious (2)", "Pathologic (3)"]

table3 = pd.DataFrame({
    "Class value": classes,

    "Precision (all features)": prec_all,
    "Precision (14 features)": prec_14,

    "Recall (all features)": rec_all,
    "Recall (14 features)": rec_14,

    "F1-score (all features)": f1_all,
    "F1-score (14 features)": f1_14
})

table3 = table3.round(2)

print("\n📊 TABLE: Class-wise Performance Comparison")
print(table3.to_string(index=False))

import numpy as np
import matplotlib.pyplot as plt

classes = ["Normal", "Suspicious", "Pathologic"]

x = np.arange(len(classes))
width = 0.25

plt.figure(figsize=(12,6))

# 🔹 Precision
plt.bar(x - width, prec_all, width, label="Precision (All Features)")
plt.bar(x, prec_14, width, label="Precision (14 Features)")

# 🔹 Recall
plt.bar(x + width, rec_all, width, label="Recall (All Features)")
plt.bar(x + 2*width, rec_14, width, label="Recall (14 Features)")

# 🔹 F1 Score (shift more)
plt.bar(x + 3*width, f1_all, width, label="F1 (All Features)")
plt.bar(x + 4*width, f1_14, width, label="F1 (14 Features)")

plt.xticks(x + width, classes)

plt.ylabel("Score", fontsize=12)
plt.title("Fig. 6: Class-wise Performance Comparison of CatBoost with and without FS", fontsize=13)

plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

x = np.arange(len(classes))
width = 0.35

plt.figure(figsize=(10,6))

# Precision comparison
plt.bar(x - width/2, prec_all, width, label="All Features")
plt.bar(x + width/2, prec_14, width, label="With FS (ANOVA)")

plt.xticks(x, classes)

plt.ylabel("Score")
plt.title("Fig. 6: Class-wise Performance Comparison of CatBoost with and without FS")

plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

import pandas as pd

data = {
    "Model": ["CatBoost"],
    "Accuracy": [97]
}

pd.DataFrame(data).to_csv("results.csv", index=False)

import os
print(os.listdir())

from google.colab import files
files.download("results.csv")

plt.figure(figsize=(14, 7))
plt.plot(table2.index, table2['MI'], label='Mutual Information (MI)', marker='o')
plt.plot(table2.index, table2['ANOVA'], label='ANOVA F-value', marker='x')
plt.plot(table2.index, table2['CC'], label='Correlation Coefficient (CC)', marker='s')

plt.title('Fig. 7: Model Accuracy vs. Number of Features for Different FS Methods', fontsize=14)
plt.xlabel('Number of Features', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.xticks(feature_sizes)
plt.yticks(np.arange(0.8, 1.01, 0.02))
plt.grid(axis='both', linestyle='--', alpha=0.7)
plt.legend(fontsize=10)

plt.tight_layout()
plt.savefig("accuracy.png", bbox_inches='tight')
plt.show()

from google.colab import files
files.download("accuracy.png")

